(() => {
  const API='https://jarvis-mobile-edition-alpha.vercel.app', authPanel=document.getElementById('auth-panel'), dashboard=document.getElementById('dashboard'), tokenInput=document.getElementById('admin-token'), authMessage=document.getElementById('auth-message'), message=document.getElementById('dashboard-message');
  let token='', session='';
  const msg=t=>message.textContent=t||'';
  async function request(path, options={}) { const headers={...(options.headers||{}),Authorization:`Bearer ${token}`}; if(session) headers['X-Jarvis-Session']=session; const r=await fetch(API+path,{...options,headers,cache:'no-store'}); const d=await r.json().catch(()=>({})); if(!r.ok) throw Error(d.message||d.error?.message||`Request failed (${r.status})`); return d; }
  const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function render(d){ const list=document.getElementById('status-list'); list.innerHTML=Object.entries(d.status||{}).map(([n,v])=>{const ok=v.status==='healthy'||v.status==='enforced'||v.value===true;return `<div class="status-row"><span>${esc(n)}</span><b class="${ok?'':'off'}">${esc((v.status|| (v?'healthy':'not_connected')).toUpperCase())}</b></div>`}).join('')||'<p class="muted">No status data.</p>'; document.getElementById('persistence-note').textContent=`Persistence: ${d.persistence?.auditLog||'unknown'} · Active sessions: ${d.sessions?.active??'—'}`; document.getElementById('flags').innerHTML=Object.entries(d.flags||{}).map(([k,v])=>`<label class="flag"><span>${esc(k)}</span><input type="checkbox" data-flag="${esc(k)}" ${v?'checked':''}></label>`).join(''); }
  function userRow(u){const states=['pending','approved','suspended','revoked'];return `<div class=\"user-row\"><div><b>${esc(u.email||u.id)}</b><small>${esc(u.phoneMasked||'No phone')} · last login: ${u.lastLoginAt?new Date(u.lastLoginAt).toLocaleString():'never'}</small></div><label>Access <select data-user-status=\"${esc(u.id)}\">${states.map(x=>`<option ${x===u.betaStatus?'selected':''}>${x}</option>`).join('')}</select></label><span class=\"user-meta\">${esc(u.planId)} · ${esc(u.subscriptionState)} · ${u.emailVerified?'verified email':'email unverified'}</span></div>`}
  async function refreshUsers(){try{const d=await request('/api/admin/users');document.getElementById('users-list').innerHTML=(d.users||[]).map(userRow).join('')||'<p class=\"muted\">No users yet.</p>';document.querySelectorAll('[data-user-status]').forEach(x=>x.onchange=async()=>{try{await request('/api/admin/users/'+encodeURIComponent(x.dataset.userStatus),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({betaStatus:x.value})});msg('Access status updated and audited.');await refreshUsers()}catch(e){msg(e.message)}})}catch(e){msg(e.message)}}
  async function refreshWaPolicy(){try{const d=await request('/api/whatsapp/policy');const p=d.policy||{};document.getElementById('wa-policy-status').innerHTML=`<b>Mode:</b> ${esc(p.mode)} · <b>Paused:</b> ${p.paused?'yes':'no'} · <b>Owner JID:</b> ${p.ownerConfigured?'configured':'not configured'}<br><b>Groups:</b> ${(p.groups||[]).filter(x=>x.enabled).length} enabled · <b>Grants:</b> ${(p.grants||[]).length} active · <b>Bridge:</b> ${esc(p.status)}<br><small>Execution: ${esc(p.execution)}</small>`}catch(e){document.getElementById('wa-policy-status').textContent=e.message}}
  async function refresh(){try{const d=await request('/api/admin/status');render(d);await refreshWaPolicy();await refreshUsers();const a=await request('/api/admin/audit-log');document.getElementById('audit-log').innerHTML=(a.entries||[]).slice(0,12).map(x=>`<li><b>${esc(x.event)}</b><small>${new Date(x.at).toLocaleString()}</small></li>`).join('')||'<li>No admin events yet.</li>'; }catch(e){msg(e.message)}}
  async function unlock(){const v=tokenInput.value.trim();if(!v){authMessage.textContent='A server token is required.';return} token=v;try{const d=await request('/api/admin/session',{method:'POST'});session=d.session;tokenInput.value='';authPanel.hidden=true;dashboard.hidden=false;await refresh()}catch(e){token='';authMessage.textContent='Access denied. Check the server token.'}}
  document.getElementById('unlock-btn').onclick=unlock; tokenInput.onkeydown=e=>{if(e.key==='Enter')unlock()}; document.getElementById('refresh-status').onclick=refresh; document.getElementById('refresh-wa-policy').onclick=refreshWaPolicy; document.getElementById('refresh-users').onclick=refreshUsers; document.getElementById('create-user').onsubmit=async e=>{e.preventDefault();try{await request('/api/admin/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:document.getElementById('new-user-email').value,phone:document.getElementById('new-user-phone').value})});e.target.reset();msg('Pending user added and audited.');await refreshUsers()}catch(err){msg(err.message)}};
  document.getElementById('generate-key').onclick=async()=>{try{const d=await request('/api/admin/activation-keys',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});const o=document.getElementById('key-result');o.textContent=`${d.key} — copy now; it will not be shown again.`;o.hidden=false;await refresh()}catch(e){msg(e.message)}};
  document.getElementById('save-flags').onclick=async()=>{const body={};document.querySelectorAll('[data-flag]').forEach(x=>body[x.dataset.flag]=x.checked);try{await request('/api/admin/feature-flags',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});msg('Feature flags updated safely.');await refresh()}catch(e){msg(e.message)}};
  document.getElementById('logout-all').onclick=async()=>{if(!confirm('Invalidate all active admin sessions?'))return;try{await request('/api/admin/logout-all',{method:'POST'});session='';token='';dashboard.hidden=true;authPanel.hidden=false;authMessage.textContent='All admin sessions invalidated.'}catch(e){msg(e.message)}};
  document.getElementById('logout-btn').onclick=async()=>{try{await request('/api/admin/logout',{method:'POST'})}catch{} session='';token='';dashboard.hidden=true;authPanel.hidden=false;authMessage.textContent='Signed out.'};
  document.getElementById('export-data').onclick=async()=>{try{const d=await request('/api/admin/privacy/export');msg(d.message)}catch(e){msg(e.message)}};
  document.getElementById('delete-data').onclick=async()=>{if(!confirm('No data will be deleted in this guarded placeholder. Continue?'))return;try{const d=await request('/api/admin/privacy/delete',{method:'POST'});msg(d.message)}catch(e){msg(e.message)}};
  document.getElementById('open-assistant').onclick=()=>window.open(new URL('./index.html',location.href).href,'kalki-assistant','popup,width=430,height=850');
})();