(()=>{
  const B='https://jarvis-mobile-edition-alpha.vercel.app', G=document.getElementById('connector-grid');
  const P=[
    ['whatsapp','WhatsApp','WA','Private JARVIS bridge only; never Zapia.','Pair the approved bridge and authorize its health check.'],
    ['gmail','Gmail','M','Read-only Gmail access through Google OAuth.','Allows KALKI to read messages only; it cannot send or delete mail.','gmail'],
    ['calendar','Google Calendar','▣','Read-only calendar access through Google OAuth.','Allows KALKI to view events only; it cannot create or edit events.','calendar'],
    ['drive','Google Drive','◆','Read-only file metadata through Google OAuth.','Allows KALKI to see file names and metadata only; it cannot change files.','drive'],
    ['youtube','YouTube','▶','Requires a server-side provider credential.','A provider credential must be configured and then safely verified.'],
    ['webSearch','Web Search','⌕','Requires a server-side search provider.','A provider credential must be configured and then safely verified.'],
    ['outlook','Outlook','O','Requires Microsoft OAuth configuration.','Microsoft authorization is required; no secret is entered here.'],
    ['slack','Slack','#','Requires Slack OAuth configuration.','Workspace authorization is required; no token is shown here.'],
    ['telegram','Telegram','➤','Requires a private Telegram bridge.','A bridge pairing and safe health verification are required.'],
    ['notion','Notion','N','Requires Notion OAuth configuration.','Notion authorization is required; no token is shown here.']
  ];
  const labels={connected:'Connected',not_connected:'Not connected',pending:'Pending authorization',expired:'Reconnect required',error:'Verification unavailable'};
  const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function card(x,meta){const m=meta||{status:'not_connected',lastVerifiedAt:null}, status=m.status||'not_connected'; const connected=status==='connected'; const link=x[5]?`${B}/api/google/oauth/start?provider=${encodeURIComponent(x[5])}`:''; const action=connected?`<button class="connector-action disconnect" data-provider="${esc(x[0])}" type="button">Disconnect</button>`:x[5]?`<a class="connector-action" href="${link}">Connect securely</a>`:`<button class="connector-action verify" data-provider="${esc(x[0])}" type="button">Check setup</button>`; const verified=m.lastVerifiedAt?`Last verified ${new Date(m.lastVerifiedAt).toLocaleString()}`:'Not verified yet'; return `<article class="connector-card"><div class="connector-top"><span class="connector-icon">${x[2]}</span><span class="connector-status ${connected?'ready':''} ${esc(status)}">${labels[status]||'Status unknown'}</span></div><h3>${x[1]}</h3><p>${x[3]}</p><small class="permission-note">${x[4]}</small><small class="verified-at">${verified}</small>${action}</article>`;}
  async function load(){G.innerHTML='<p class="loading">Checking secure connector status…</p>';try{const r=await fetch(`${B}/api/connectors/status`,{cache:'no-store'}),d=await r.json();if(!r.ok||!d.ok)throw Error();G.innerHTML=P.map(x=>card(x,d.providers?.[x[0]])).join('');bind();}catch{G.innerHTML=P.map(x=>card(x)).join('');G.insertAdjacentHTML('afterbegin','<p class="loading">Secure status unavailable; showing conservative Not connected states.</p>');bind();}}
  function bind(){G.querySelectorAll('.verify').forEach(b=>b.onclick=async()=>{b.disabled=true;b.textContent='Checking…';try{const r=await fetch(`${B}/api/connectors/${encodeURIComponent(b.dataset.provider)}/verify`,{cache:'no-store'});const d=await r.json();alert(d.message||'Provider remains pending until authorization and a safe read-only verification succeed.');}catch{alert('Verification is unavailable. Nothing was executed.');}finally{load();}});G.querySelectorAll('.disconnect').forEach(b=>b.onclick=async()=>{if(!confirm('Disconnect this provider from KALKI?'))return;try{const r=await fetch(`${B}/api/google/disconnect`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider:b.dataset.provider})});if(!r.ok)throw Error();load();}catch{alert('Disconnect requires the protected JARVIS admin session. No provider action was performed.');}});}
  load();
})();
