// KALKI Interaction Brain foundation: deterministic conversation policy and scaffolding.
// This module never sends messages, schedules work, or performs provider actions.
const DEFAULT_POLICY = Object.freeze({version:1,explicitActionsOnly:true,backgroundReplies:false,proactiveGreeting:false,askFollowUps:true,memoryMode:'user-controlled',unknownDataPolicy:'say-unavailable'});
const ACTION_WORDS = /\b(open|launch|start|send|reply|message|tell|search|find|create|add|schedule|show|read|save|remember|plan|organize|draft|transcribe|summarize|follow[- ]?up|check in)\b|చెప్పు|పంపు|చూడు|వెతుకు|తెరువు/i;
const looksLikeGreeting = text => /^(hi|hello|hey|good morning|good evening|namaste|హాయ్|నమస్కారం)\b/i.test(String(text||'').trim());
const looksLikeMorningBrief = text => /\b(morning|today|day|daily)\b.*\b(brief|summary|plan|schedule|work)\b|\b(my|today'?s)\s+(day|schedule|work)\b/i.test(String(text||''));
function classify(text=''){const value=String(text).trim(),lower=value.toLowerCase();const externalAction=ACTION_WORDS.test(value);let intent='conversation';if(looksLikeGreeting(value))intent='greeting';else if(looksLikeMorningBrief(value))intent='daily_brief';else if(/\b(remember|memory|save this|forget)\b/i.test(value))intent='memory';else if(/\b(whatsapp|message|reply|send)\b/i.test(value))intent='messaging';else if(/\b(calendar|meeting|event|schedule)\b/i.test(value))intent='calendar';else if(/\b(task|todo|reminder)\b/i.test(value))intent='tasks';else if(/\b(search|google|web|news)\b/i.test(value))intent='search';return {intent,externalAction,isGreeting:looksLikeGreeting(value),isBriefRequest:looksLikeMorningBrief(value),normalized:lower.slice(0,1000)};}
function clarificationFor(text=''){const c=classify(text),value=String(text);if(!c.externalAction)return null;if(c.intent==='messaging'&&/\b(send|message|reply)\b/i.test(value)&&!(/\bto\b|@[\w.-]+|\+?\d[\d -]{6,}/i.test(value)))return {code:'MISSING_RECIPIENT',question:'Who should I message? I will prepare it first and wait for your confirmation before sending.'};if(c.intent==='messaging'&&/\b(send|message|reply)\b/i.test(value)&&!/(?:message|say|text)\s+.{2,}/i.test(value))return {code:'MISSING_MESSAGE',question:'What should the message say? I will not send anything without your explicit confirmation.'};if(c.intent==='calendar'&&/\b(schedule|create|add)\b/i.test(value)&&!/\b(at|on|tomorrow|today|am|pm|\d{1,2}:\d{2})\b/i.test(value))return {code:'MISSING_TIME',question:'What date and time should I use? Calendar is not connected, so I can only prepare a draft for now.'};if(c.intent==='tasks'&&/\b(create|add|set|remind)\b/i.test(value)&&value.split(/\s+/).length<5)return {code:'MISSING_TASK_DETAIL',question:'What exactly should the task or reminder say, and when should it be due?'};return null;}
function contextSignals(messages=[]){const recent=Array.isArray(messages)?messages.slice(-12).filter(x=>x&&typeof x.text==='string'):[];const lastUser=[...recent].reverse().find(x=>x.type==='user'||/^you$/i.test(x.sender||''));const lastAssistant=[...recent].reverse().find(x=>x.type==='ai'||/^kalki$/i.test(x.sender||''));return {messageCount:recent.length,lastUserText:lastUser?.text?.slice(0,500)||null,lastAssistantText:lastAssistant?.text?.slice(0,500)||null,continuityAvailable:recent.length>0};}
function morningGreetingPreview({profile={},connectors={}}={}){const name=String(profile.displayName||'').trim();const calendar=connectors.calendar==='connected'?'Calendar data can be included after a verified read-only connection.':'Calendar is not connected, so no events are assumed.';const tasks=connectors.tasks==='connected'?'Task data can be included after a verified read-only connection.':'Tasks are not connected, so no tasks are assumed.';return {enabled:false,scheduled:false,sent:false,preview:`Good morning${name?`, ${name}`:''}. I’m ready when you are. ${calendar} ${tasks}`,requirements:['explicit opt-in','scheduler/notification delivery','verified calendar/tasks connectors'],policy:DEFAULT_POLICY};}
function analyze({text='',messages=[],profile={},preferences={}}={}){const classification=classify(text),clarification=preferences.askFollowUps===false?null:clarificationFor(text);return {ok:true,policy:DEFAULT_POLICY,classification,clarification,signals:contextSignals(messages),interaction:clarification?'clarification':classification.isBriefRequest?'brief_preview':'respond',profile:{displayName:String(profile.displayName||'').slice(0,60),language:profile.language||'auto',responseStyle:profile.responseStyle||'short'}};}
module.exports={DEFAULT_POLICY,classify,clarificationFor,contextSignals,morningGreetingPreview,analyze};
