const http=require('node:http');const {URL}=require('node:url');const SKILLS=require('./skills');const GOOGLE=require('./google-oauth');
const PORT=Number(process.env.PORT||8787),API_TOKEN=process.env.JARVIS_API_TOKEN||'',ALLOWED_ORIGIN=process.env.ALLOWED_ORIGIN||'*',WPP_BRIDGE_URL=process.env.WPP_BRIDGE_URL||'',WPP_BRIDGE_TOKEN=process.env.WPP_BRIDGE_TOKEN||'';
function json(res,status,body){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Access-Control-Allow-Origin':ALLOWED_ORIGIN,'Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET, POST, OPTIONS'});res.end(JSON.stringify(body));}
function authorized(req){return Boolean(API_TOKEN)&&req.headers.authorization===`Bearer ${API_TOKEN}`;}
function readBody(req){return new Promise((resolve,reject)=>{let data='';req.on('data',c=>{data+=c;if(data.length>262144)req.destroy();});req.on('end',()=>{try{resolve(data?JSON.parse(data):{});}catch{reject(new Error('Invalid JSON'));}});req.on('error',reject);});}
function detectSkill(text=''){const p={whatsapp:/whatsapp|message|reply|chat/i,search:/google|search|web|news|weather/i,youtube:/youtube|video/i,email:/email|mail|gmail|outlook/i,calendar:/calendar|schedule|meeting|event/i,tasks:/task|reminder|todo/i,contacts:/contact|phone number|address book/i,drive:/drive|file|folder|upload|download/i,documents:/pdf|word|docx|excel|xlsx|spreadsheet|powerpoint|pptx/i,travel:/flight|hotel|travel|trip/i,places:/restaurant|place|shop|near me|directions/i,prices:/price|cost|cheap|compare|buy/i,media:/image|photo|picture|video edit/i,automation:/automate|automation|workflow|multi[- ]step/i,memory:/remember|memory|save this/i};return Object.keys(p).find(k=>p[k].test(text))||null;}
function explicit(text=''){return /\b(open|launch|start|send|reply|message|tell|search|find|create|add|schedule|show|read|save|remember)\b|chey|pampu|cheppu|choodu|vetuku|teruvu/i.test(text);}
async function command(body){const text=String(body.text||'').trim();if(!text)throw new Error('Command text is required');const skill=detectSkill(text);if(!skill||!explicit(text))return {executed:false,explicitOnly:true,reason:'Ask with an explicit action.'};if(skill==='whatsapp')return {executed:false,skill,action:'send_or_reply',requires:['recipient','message'],providerConnected:Boolean(WPP_BRIDGE_URL&&WPP_BRIDGE_TOKEN),message:'No message was sent without an explicit complete command and connected bridge.'};return {executed:false,skill,providerConnected:false,skillInfo:SKILLS[skill],message:`${SKILLS[skill].name} is recognized, but its provider is not connected. Nothing was executed.`};}
const server=http.createServer(async(req,res)=>{if(req.method==='OPTIONS')return json(res,204,{});const url=new URL(req.url,`http://${req.headers.host}`);if(req.method==='GET'&&url.pathname==='/api/health')return json(res,200,{ok:true,service:'jarvis-backend',explicitActionsOnly:true,backgroundReplies:false,whatsappBridge:Boolean(WPP_BRIDGE_URL&&WPP_BRIDGE_TOKEN),googleOAuth:true,skills:Object.keys(SKILLS)});
if(req.method==='GET'&&url.pathname==='/api/google/oauth/start'){const name=url.searchParams.get('provider');if(!GOOGLE.provider(name))return json(res,400,{ok:false,message:'Unsupported Google provider',providers:Object.keys(GOOGLE.PROVIDERS)});try{res.writeHead(302,{Location:GOOGLE.authorizationUrl(name),'Cache-Control':'no-store'});return res.end();}catch(e){return json(res,503,{ok:false,message:e.message});}}
if(req.method==='GET'&&url.pathname==='/api/google/oauth/callback'){const state=GOOGLE.consumeState(url.searchParams.get('state'));if(!state)return json(res,400,{ok:false,message:'Invalid or expired Google OAuth state'});if(url.searchParams.get('error'))return json(res,400,{ok:false,message:'Google authorization was not completed'});const code=url.searchParams.get('code');if(!code)return json(res,400,{ok:false,message:'Google authorization code is missing'});try{await GOOGLE.secureTokenStore.set(state.provider,await GOOGLE.exchangeCode(code));res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});return res.end('<!doctype html><title>Google connected</title><p>Google account connected. You may close this window.</p>');}catch(e){return json(res,503,{ok:false,message:e.message});}}
try{if((req.method==='GET'&&url.pathname==='/api/google/status')||(req.method==='POST'&&url.pathname==='/api/google/disconnect')){if(!authorized(req))return json(res,401,{ok:false,message:'Google provider management requires the server token.'});if(req.method==='POST'){const b=await readBody(req);if(!GOOGLE.provider(b.provider))return json(res,400,{ok:false,message:'Unsupported Google provider'});await GOOGLE.secureTokenStore.delete(b.provider);return json(res,200,{ok:true,provider:b.provider,disconnected:true});}const providers={};for(const name of Object.keys(GOOGLE.PROVIDERS)){try{providers[name]=Boolean(await GOOGLE.secureTokenStore.get(name));}catch{providers[name]=false;}}return json(res,200,{ok:true,providers,note:'Connected status only; no access tokens are returned.'});}if(req.method==='POST'&&url.pathname==='/api/command')return json(res,200,{ok:true,result:await command(await readBody(req))});if(req.method==='POST'&&url.pathname==='/api/whatsapp/send'){if(!authorized(req))return json(res,401,{ok:false,message:'Provider execution requires the server token.'});return json(res,200,{ok:true,result:{configured:Boolean(WPP_BRIDGE_URL&&WPP_BRIDGE_TOKEN),executed:false,message:'WhatsApp sending remains explicit-command-only and is not configured.'}});}return json(res,404,{ok:false,message:'Not found'});}catch(e){return json(res,500,{ok:false,message:e.message});}});server.listen(PORT,()=>console.log(`JARVIS backend listening on ${PORT}`));
