import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';

const jsx = await readFile(new URL('./src/main.jsx', import.meta.url), 'utf8');
const css = await readFile(new URL('./src/styles.css', import.meta.url), 'utf8');
const html = await readFile(new URL('./index.html', import.meta.url), 'utf8');
const packageJson = JSON.parse(await readFile(new URL('./package.json', import.meta.url), 'utf8'));
assert.match(jsx, /import logoAsset from '\.\/assets\/kalki-logo\.jpg'/, 'the user-provided KALKI logo must be bundled');
assert.ok(packageJson.dependencies['framer-motion'], 'Framer Motion must be installed');
assert.ok(packageJson.devDependencies.tailwindcss, 'Tailwind CSS must be installed');
assert.ok(packageJson.dependencies['img-fx'], 'img-fx must be installed');
assert.ok(packageJson.dependencies.three, 'three must be installed for the image effect');
assert.match(jsx, /<ImageGeneration/, 'the Libraries.dev image reveal must be integrated');
assert.match(jsx, /pixels-organic.*pixels-mechanic.*sweep-gradient/s, 'all image reveal presets must be available');
assert.match(html, /<html lang="en">/, 'public site must be English-only');
assert.match(html, /jarvis-mobile-edition\/frontend\//, 'KALKI app backlink must point to the existing app');
assert.match(jsx, /useReducedMotion/, 'motion must respect reduced-motion preferences');
assert.match(css, /prefers-reduced-motion:\s*reduce/, 'CSS reduced-motion fallback must be present');
assert.match(jsx, /SIMULATOR ONLY/, 'social integration status must remain honest');
assert.match(jsx, /NOT RELEASED/, 'Android release status must remain honest');
assert.match(jsx, /NOT CONFIGURED/, 'billing status must remain honest');
assert.ok(!/https?:\/\/(?:www\.)?irisxai\.in/i.test(jsx), 'reference website must not be linked as copied content');
console.log('Static checks passed: image reveal, presets, English language, app backlink, reduced motion, honest status labels, reference-site independence.');
